networks:
  kafka-cluster:
    name: kafka-cluster
    driver: bridge

volumes:
  redis:
  zookeeperController:
  zookeeper1:
  zookeeper2:
  zookeeper-cluster3:
  kafkaController:
  kafka1:
  kafka2:
  kafka1-cluster3:
  kafka2-cluster3:
  kafka3-cluster3:

services:
  redis:
    image: bitnami/redis:6.2
    container_name: redis
    environment:
      - REDIS_AOF_ENABLED=yes
      - REDIS_APPENDFSYNC=everysec
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    volumes:
      - redis:/bitnami/redis/data
    networks:
      - kafka-cluster

  zookeeperController:
    image: bitnami/zookeeper:3.6.2
    container_name: zookeeperController
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - zookeeperController:/bitnami/zookeeper
    networks:
      - kafka-cluster

  zookeeper1:
    image: bitnami/zookeeper:3.6.2
    container_name: zookeeper1
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - zookeeper1:/bitnami/zookeeper
    networks:
      - kafka-cluster

  zookeeper2:
    image: bitnami/zookeeper:3.6.2
    container_name: zookeeper2
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - zookeeper2:/bitnami/zookeeper
    networks:
      - kafka-cluster

  zookeeper-cluster3:
    image: bitnami/zookeeper:3.6.2
    container_name: zookeeper-cluster3
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - zookeeper-cluster3:/bitnami/zookeeper
    networks:
      - kafka-cluster

  kafkaController:
    image: bitnami/kafka:3.1.0
    container_name: kafkaController
    ports:
      - '19093:19093'
    environment:
      - KAFKA_CFG_BROKER_ID=101
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeperController:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:19093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafkaController:9092,EXTERNAL://localhost:19093
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=false
    depends_on:
      - zookeeperController
    volumes:
      - kafkaController:/bitnami/kafka
    networks:
      - kafka-cluster

  kafka1:
    image: bitnami/kafka:3.1.0
    container_name: kafka1
    ports:
      - '9093:9093'
    environment:
      - KAFKA_CFG_BROKER_ID=101
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper1:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka1:9092,EXTERNAL://localhost:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=false
    depends_on:
      - zookeeper1
    volumes:
      - kafka1:/bitnami/kafka
    networks:
      - kafka-cluster

  kafka2:
    image: bitnami/kafka:3.1.0
    container_name: kafka2
    ports:
      - '9094:9094'
    environment:
      - KAFKA_CFG_BROKER_ID=101
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper2:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka2:9092,EXTERNAL://localhost:9094
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=false
    depends_on:
      - zookeeper2
    volumes:
      - kafka2:/bitnami/kafka
    networks:
      - kafka-cluster

  kafka1-cluster3:
    image: bitnami/kafka:3.1.0
    container_name: kafka1-cluster3
    ports:
      - '9392:9392'
    environment:
      - KAFKA_CFG_BROKER_ID=101
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-cluster3:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9392
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka1-cluster3:9092,EXTERNAL://localhost:9392
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=false
      - KAFKA_CFG_DEFAULT_REPLICATION_FACTOR=3
    depends_on:
      - zookeeper-cluster3
    volumes:
      - kafka1-cluster3:/bitnami/kafka
    networks:
      - kafka-cluster

  kafka2-cluster3:
    image: bitnami/kafka:3.1.0
    container_name: kafka2-cluster3
    ports:
      - '9393:9393'
    environment:
      - KAFKA_CFG_BROKER_ID=102
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-cluster3:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9393
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka2-cluster3:9092,EXTERNAL://localhost:9393
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=false
      - KAFKA_CFG_DEFAULT_REPLICATION_FACTOR=3
    depends_on:
      - zookeeper-cluster3
    volumes:
      - kafka2-cluster3:/bitnami/kafka
    networks:
      - kafka-cluster

  kafka3-cluster3:
    image: bitnami/kafka:3.1.0
    container_name: kafka3-cluster3
    ports:
      - '9394:9394'
    environment:
      - KAFKA_CFG_BROKER_ID=103
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-cluster3:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9394
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka3-cluster3:9092,EXTERNAL://localhost:9394
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=false
      - KAFKA_CFG_DEFAULT_REPLICATION_FACTOR=3
    depends_on:
      - zookeeper-cluster3
    volumes:
      - kafka3-cluster3:/bitnami/kafka
    networks:
      - kafka-cluster
